
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workshop-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb+srv://39-yan-yon:HX6yXQjAHzfjuD2n@cluster0.ksjqymp.mongodb.net/motorcycle-workshop?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your-jwt-secret-change-in-production
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "3001:3001"
    networks:
      - workshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workshop-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - workshop-network

volumes: {}

networks:
  workshop-network:
    driver: bridge
